version: '3.0'

services:
  postgres:
    image: postgres:15
    container_name : ${CONTAINER_NAME}
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - 5432:5432 #No Linux só funcionou sem usar variável de ambiente. 
    #  - ${POSTGRES_LOCAL_PORT}:${POSTGRES_CONTAINER_PORT}


# volumes:
#   postgres:
